default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coffee_shop_development

test:
  <<: *default
  database: coffee_shop_test

production:
  <<: *default
  database: coffee_shop_production
  username: coffee_shop
  password: <%= ENV["COFFEE_SHOP_DATABASE_PASSWORD"] %>
